import type { PartnerIconName, PartnersContent } from "./partnersTypes";

export const PARTNER_ICON_OPTIONS: { value: PartnerIconName; label: string }[] = [
  { value: "sparkles", label: "Sparkles" },
  { value: "music", label: "Music" },
  { value: "mic", label: "Host" },
  { value: "camera", label: "Camera" },
  { value: "video", label: "Video" },
  { value: "building", label: "Venue" },
  { value: "flower", label: "Decor" },
  { value: "cake", label: "Cake" },
  { value: "party", label: "Fireworks" },
  { value: "heart", label: "Wedding" },
  { value: "palette", label: "Design" },
  { value: "more", label: "More" },
];

export const DEFAULT_PARTNERS_CONTENT: PartnersContent = {
  version: 1,
  updatedAt: "2026-06-10T00:00:00.000Z",
  page: {
    eyebrow: "4ever.am marketplace",
    title: "Գործընկերներ",
    subtitle:
      "Ընտրեք հարսանեկան ծառայություններ մեկ վայրում՝ երաժշտություն, լուսանկարահանում, ռեստորաններ, դեկոր և ավելին:",
    heroImage: "/template_previews/img1.webp",
    helpPanelTitle: "Չե՞ք գտնում ճիշտ գործընկերոջը",
    helpPanelDescription:
      "Գրեք 4ever.am թիմին, և մենք կօգնենք ընտրել հարմար տարբերակ ձեր օրվա ոճին, քաղաքին և բյուջեին համապատասխան:",
    contactPhone: "",
    messageLink: "https://t.me/4everam",
    telegramLink: "https://t.me/4everam",
    whatsappLink: "",
    instagramLink: "https://www.instagram.com/4ever.am",
    showExamples: true,
    showHelpPanel: true,
  },
  categories: [
    { id: "bands", label: "Բենդեր", icon: "music", enabled: true, order: 10 },
    { id: "tamada", label: "Թամադա", icon: "mic", enabled: true, order: 20 },
    { id: "artists", label: "Նկարիչներ", icon: "palette", enabled: true, order: 30 },
    { id: "photo-video", label: "Ֆոտո և վիդեո", icon: "camera", enabled: true, order: 40 },
    { id: "restaurants", label: "Ռեստորաններ", icon: "building", enabled: true, order: 50 },
    { id: "decor", label: "Դեկոր և ձևավորում", icon: "flower", enabled: true, order: 60 },
    { id: "cakes", label: "Տորթեր", icon: "cake", enabled: true, order: 70 },
    { id: "fireworks", label: "Հրավառություն", icon: "party", enabled: true, order: 80 },
    { id: "other", label: "Ավելին", icon: "more", enabled: true, order: 90 },
  ],
  vendors: [
    {
      id: "aurora-live-band",
      name: "Aurora Live Band",
      categoryId: "bands",
      shortDescription: "Կենդանի երաժշտություն արարողության և երեկույթի համար:",
      fullDescription:
        "Ֆիկտիվ ցուցադրական գործընկեր՝ նախատեսված marketplace դիզայնը և builder փորձը ստուգելու համար: Փաթեթները կարող են ներառել արարողության երաժշտություն, ընթրիքի մեղմ կատարումներ և երեկոյան ծրագիր:",
      city: "Երևան",
      priceFrom: 280000,
      currency: "AMD",
      displayPrice: "սկսած 280,000 ֏",
      rating: 4.9,
      reviewCount: 42,
      popularity: 98,
      mainImage: "/template_previews/img2.webp",
      galleryImages: ["/template_previews/img2.webp", "/template_previews/img1.webp", "/template_previews/img4.webp"],
      phone: "",
      messageLink: "",
      telegramLink: "",
      whatsappLink: "",
      instagramLink: "",
      websiteLink: "",
      packages: [
        { id: "ceremony", name: "Ceremony", price: "120,000 ֏", description: "Արարողության կենդանի կատարում" },
        { id: "evening", name: "Full evening", price: "280,000 ֏", description: "Երաժշտական ամբողջական ծրագիր" },
      ],
      tags: ["live", "music", "featured"],
      status: "published",
      enabled: true,
      featured: true,
      featuredOrder: 10,
      updatedAt: "2026-06-10T00:00:00.000Z",
    },
    {
      id: "vard-host",
      name: "Vard Ceremony Host",
      categoryId: "tamada",
      shortDescription: "Հարսանեկան երեկոյի վարում՝ ջերմ և կազմակերպված ոճով:",
      fullDescription:
        "Ֆիկտիվ ցուցադրական գործընկեր թամադայի քարտերի, կապի դաշտերի և մանրամասների պատուհանի համար:",
      city: "Երևան",
      priceFrom: 180000,
      currency: "AMD",
      displayPrice: "սկսած 180,000 ֏",
      rating: 4.8,
      reviewCount: 36,
      popularity: 91,
      mainImage: "/attached_assets/couple11.jpg",
      galleryImages: ["/attached_assets/couple11.jpg", "/template_previews/img5.webp"],
      phone: "",
      messageLink: "",
      telegramLink: "",
      whatsappLink: "",
      instagramLink: "",
      websiteLink: "",
      packages: [
        { id: "reception", name: "Reception", price: "180,000 ֏", description: "Երեկոյի հիմնական վարում" },
        { id: "coordination", name: "Coordination", price: "60,000 ֏", description: "Ժամանակացույցի աջակցություն" },
      ],
      tags: ["host", "ceremony"],
      status: "published",
      enabled: true,
      featured: true,
      featuredOrder: 20,
      updatedAt: "2026-06-10T00:00:00.000Z",
    },
    {
      id: "lusin-photo-video",
      name: "Lusin Photo Video",
      categoryId: "photo-video",
      shortDescription: "Ֆոտո և վիդեո փաթեթներ՝ հարսանիքի ամբողջ օրվա համար:",
      fullDescription:
        "Ֆիկտիվ ցուցադրական գործընկեր, որը ցույց է տալիս gallery, rating և package դաշտերի աշխատանքը:",
      city: "Գյումրի",
      priceFrom: 390000,
      currency: "AMD",
      displayPrice: "սկսած 390,000 ֏",
      rating: 4.7,
      reviewCount: 29,
      popularity: 88,
      mainImage: "/template_previews/img4.webp",
      galleryImages: ["/template_previews/img4.webp", "/template_previews/img3.webp", "/template_previews/img1.webp"],
      phone: "",
      messageLink: "",
      telegramLink: "",
      whatsappLink: "",
      instagramLink: "",
      websiteLink: "",
      packages: [
        { id: "photo", name: "Photo day", price: "220,000 ֏", description: "Լուսանկարահանում ամբողջ օրվա համար" },
        { id: "photo-video", name: "Photo + video", price: "390,000 ֏", description: "Լուսանկար և տեսանյութ" },
      ],
      tags: ["photo", "video"],
      status: "published",
      enabled: true,
      featured: true,
      featuredOrder: 30,
      updatedAt: "2026-06-10T00:00:00.000Z",
    },
    {
      id: "garden-demo-hall",
      name: "Garden Demo Hall",
      categoryId: "restaurants",
      shortDescription: "Ռեստորանային սրահ և բացօթյա արարողության տարածք:",
      fullDescription:
        "Ֆիկտիվ ցուցադրական գործընկեր վայրերի քարտերի համար: Չի ներկայացնում իրական հաճախորդի կամ ռեստորանի տվյալներ:",
      city: "Դիլիջան",
      priceFrom: 650000,
      currency: "AMD",
      displayPrice: "սկսած 650,000 ֏",
      rating: 4.6,
      reviewCount: 74,
      popularity: 94,
      mainImage: "/attached_assets/Restaurant1_1758400398786.jfif",
      galleryImages: ["/attached_assets/Restaurant1_1758400398786.jfif", "/attached_assets/1_1755890746399.jpg"],
      phone: "",
      messageLink: "",
      telegramLink: "",
      whatsappLink: "",
      instagramLink: "",
      websiteLink: "",
      packages: [
        { id: "banquet", name: "Banquet hall", price: "650,000 ֏", description: "Սրահի վարձակալություն" },
        { id: "garden", name: "Garden ceremony", price: "120,000 ֏", description: "Բացօթյա արարողության գոտի" },
      ],
      tags: ["venue", "garden"],
      status: "published",
      enabled: true,
      featured: false,
      featuredOrder: 40,
      updatedAt: "2026-06-10T00:00:00.000Z",
    },
    {
      id: "rose-demo-decor",
      name: "Rose Demo Decor",
      categoryId: "decor",
      shortDescription: "Ծաղկային դեկոր, սեղանի ձևավորում և արարողության կամար:",
      fullDescription:
        "Ֆիկտիվ ցուցադրական գործընկեր դեկորի կատեգորիայի համար: Օգտագործվում է միայն marketplace բովանդակության օրինակի համար:",
      city: "Երևան",
      priceFrom: 240000,
      currency: "AMD",
      displayPrice: "սկսած 240,000 ֏",
      rating: 4.8,
      reviewCount: 33,
      popularity: 90,
      mainImage: "/attached_assets/floral-background1.jpg",
      galleryImages: ["/attached_assets/floral-background1.jpg", "/template_previews/img1.webp"],
      phone: "",
      messageLink: "",
      telegramLink: "",
      whatsappLink: "",
      instagramLink: "",
      websiteLink: "",
      packages: [
        { id: "table", name: "Table decor", price: "90,000 ֏", description: "Սեղանի հիմնական ձևավորում" },
        { id: "full", name: "Full venue", price: "240,000 ֏", description: "Ամբողջական դեկոր" },
      ],
      tags: ["decor", "flowers"],
      status: "published",
      enabled: true,
      featured: false,
      featuredOrder: 50,
      updatedAt: "2026-06-10T00:00:00.000Z",
    },
    {
      id: "sweet-demo-atelier",
      name: "Sweet Demo Atelier",
      categoryId: "cakes",
      shortDescription: "Հարսանեկան տորթեր և քաղցր սեղանի ձևավորում:",
      fullDescription:
        "Ֆիկտիվ ցուցադրական գործընկեր տորթերի կատեգորիայի, tags և package դաշտերի համար:",
      city: "Երևան",
      priceFrom: 120000,
      currency: "AMD",
      displayPrice: "սկսած 120,000 ֏",
      rating: 4.9,
      reviewCount: 25,
      popularity: 84,
      mainImage: "/template_previews/img5.webp",
      galleryImages: ["/template_previews/img5.webp", "/attached_assets/floral-background1.jpg"],
      phone: "",
      messageLink: "",
      telegramLink: "",
      whatsappLink: "",
      instagramLink: "",
      websiteLink: "",
      packages: [
        { id: "cake", name: "Two-tier cake", price: "120,000 ֏", description: "Երկհարկանի տորթ" },
        { id: "dessert", name: "Dessert table", price: "180,000 ֏", description: "Քաղցր սեղան" },
      ],
      tags: ["cake", "dessert"],
      status: "published",
      enabled: true,
      featured: false,
      featuredOrder: 60,
      updatedAt: "2026-06-10T00:00:00.000Z",
    },
  ],
  examples: [
    {
      id: "example-live-music",
      title: "Երաժշտական երեկո",
      categoryId: "bands",
      linkedVendorId: "aurora-live-band",
      image: "/template_previews/img2.webp",
      enabled: true,
      order: 10,
    },
    {
      id: "example-photo-video",
      title: "Ֆոտո և վիդեո փաթեթ",
      categoryId: "photo-video",
      linkedVendorId: "lusin-photo-video",
      image: "/template_previews/img4.webp",
      enabled: true,
      order: 20,
    },
    {
      id: "example-decor",
      title: "Ծաղկային ձևավորում",
      categoryId: "decor",
      linkedVendorId: "rose-demo-decor",
      image: "/attached_assets/floral-background1.jpg",
      enabled: true,
      order: 30,
    },
  ],
};
