// Auto-generated — re-exports types from translations-prototype/types.ts
export type {
  Locale,
  LS,
  NavItem,
  Navigation,
  HeroConfig,
  CtaButton,
  Chip,
  TemplateCard,
  TemplatesSection,
  HowItWorksStep,
  HowItWorksSection,
  FeatureItem,
  FeaturesSection,
  BenefitItem,
  MobileExperienceSection,
  ActionChip,
  FaqItem,
  FaqSection,
  ContactButton,
  ContactSection,
  TrustItem,
  FooterSection,
  HomepageContent,
  ValidationWarning,
  IconKey,
} from "../../pages/translations-prototype/types";
