export const plannerText = {
  app: {
    name: "4ever Planner",
    weddingDate: "Wedding Date",
    coupleName: "Aram & Ani",
    greeting: "Welcome back",
    greetingSub: "Here's what's happening with your wedding.",
  },
  nav: {
    dashboard: "Dashboard",
    guests: "Guests",
    tables: "Tables",
    budget: "Budget",
    more: "More",
    settings: "Settings",
  },
  common: {
    add: "Add",
    edit: "Edit",
    delete: "Delete",
    duplicate: "Duplicate",
    save: "Save",
    cancel: "Cancel",
    close: "Close",
    search: "Search",
    reset: "Reset",
    export: "Export",
    import: "Import",
    apply: "Apply",
    remove: "Remove",
    total: "Total",
    paid: "Paid",
    remaining: "Remaining",
    planned: "Planned",
    actual: "Actual",
    empty: "Empty",
    back: "Back",
    confirm: "Confirm",
    seats: "seats",
    guests: "guests",
    tables: "tables",
    of: "of",
    free: "free",
    seated: "seated",
    notes: "Notes",
    persons: "persons",
    all: "All",
  },
  dashboard: {
    title: "Dashboard",
    weddingOverview: "Wedding Overview",
    guestOverview: "Guest Overview",
    seatingOverview: "Seating Overview",
    budgetOverview: "Budget Overview",
    upcomingTasks: "Upcoming Tasks",
    recentExpenses: "Recent Expenses",
    quickActions: "Quick Actions",
    totalGuests: "Total Guests",
    tables: "Tables",
    totalSeated: "Seated",
    totalBudget: "Total Budget",
    coming: "Coming",
    waiting: "Waiting",
    notComing: "Not Coming",
    noResponse: "No Response",
    totalSeats: "Total Seats",
    freeSeats: "Free Seats",
    daysTo: "days to go",
    addGuest: "Add Guest",
    generatePlan: "Generate Seating Plan",
    addExpense: "Add Expense",
    weddingOf: "Wedding of",
    attending: "Attending",
    seated: "Seated",
    paid: "Paid",
    remaining: "Remaining",
    daysLeft: "days left",
    noGuests: "No guests added yet",
    filled: "filled",
    totalTables: "Tables",
    assigned: "Assigned",
    available: "Available",
    spent: "Spent",
    seeAllGuests: "See all guests",
    viewFloorPlan: "View floor plan",
    viewGuests: "View guests",
    viewTables: "View tables",
    viewSeating: "View seating",
    viewBudget: "View budget",
    seeAllTasks: "See all tasks",
    recentBudgetItems: "Recent Budget Items",
    viewAllExpenses: "View all expenses",
    welcomePrefix: "Welcome back,",
  },
  rsvp: {
    invited: "Invited",
    coming: "Coming",
    not_coming: "Not Coming",
    waiting: "Waiting",
    maybe: "Maybe",
  },
  guestSide: {
    bride: "Bride Side",
    groom: "Groom Side",
    both: "Both Sides",
    other: "Other",
  },
  guests: {
    title: "Guests",
    subtitle: "Manage your guest list and RSVP statuses.",
    searchPlaceholder: "Search guests...",
    totalGuests: "Total Guests",
    all: "All",
    coming: "Coming",
    waiting: "Waiting",
    notComing: "Not Coming",
    maybe: "Maybe",
    invited: "Invited",
    unseated: "Unseated",
    addGuest: "Add Guest",
    editGuest: "Edit Guest",
    fullName: "Full Name",
    fullNamePlaceholder: "e.g. Aram Petrosyan",
    phone: "Phone",
    phonePlaceholder: "+374…",
    email: "Email",
    emailPlaceholder: "email@example.com",
    rsvpStatus: "RSVP Status",
    guestCount: "Guest Count",
    side: "Side",
    groupName: "Group / Family",
    groupNamePlaceholder: "e.g. Petrosyan Family",
    dietaryNotes: "Dietary Notes",
    dietaryNotesPlaceholder: "Vegetarian, gluten-free…",
    notes: "Notes",
    notesPlaceholder: "Any additional notes…",
    tableAssignment: "Table",
    noGuests: "No guests yet",
    noGuestsDesc: "Add your first guest to start planning.",
    noResults: "No guests match your search.",
    deleteConfirm: "Delete this guest?",
    emptyTitle: "No guests yet",
    emptyDesc: "Add your first guest to start planning.",
    emptySearch: "No guests match your search.",
    noUnassignedGuests: "All coming guests are already seated.",
  },
  tables: {
    title: "Tables",
    subtitle: "Create tables, choose shapes, and assign guests to seats.",
    table: "Table",
    addTable: "Add Table",
    editTable: "Edit Table",
    deleteTable: "Delete Table",
    generatePlan: "Generate Seating Plan",
    manageSeats: "Manage Seats",
    locked: "Locked",
    tableName: "Table Name",
    tableNamePlaceholder: "e.g. Table 1, Head Table…",
    tableShape: "Shape",
    seatCount: "Number of Seats",
    notes: "Notes",
    notesPlaceholder: "Optional notes…",
    totalSeats: "Total Seats",
    seated: "Seated",
    free: "Free",
    noTables: "No tables yet",
    noTablesDesc: "Generate a seating plan or add a table manually.",
    noResults: "No tables match your search.",
    deleteConfirm: "Delete this table? Guests will be unassigned.",
    searchPlaceholder: "Search tables…",
    totalTables: "Tables",
    emptyTitle: "No tables yet",
    emptyDesc: "Generate a seating plan or add a table manually.",
    shape: "Shape",
    capacity: "Capacity",
    available: "Available",
  },
  tableShapes: {
    circle: "Round",
    square: "Square",
    rectangle: "Rectangle",
    long: "Long Banquet",
    oval: "Oval",
    head: "Head Table",
  },
  seats: {
    title: "Seat Assignment",
    assignedGuests: "Assigned Guests",
    emptySeat: "Empty",
    tapToAssign: "Tap a seat to assign or remove a guest",
    selectGuest: "Select Guest",
    searchGuest: "Search guest…",
    noUnassigned: "All coming guests are seated",
    assigned: "assigned",
    unassign: "Remove",
    seatLabel: "Seat",
    remove: "Remove",
    empty: "Empty Seat",
    assign: "Assign",
    pickGuest: "Pick a Guest",
  },
  budget: {
    title: "Budget",
    subtitle: "Track planned costs, payments and remaining expenses.",
    totalBudget: "Total Budget",
    estimatedBudget: "Estimated",
    paid: "Paid",
    remaining: "Remaining",
    addExpense: "Add Expense",
    editExpense: "Edit Expense",
    category: "Category",
    itemName: "Item Name",
    itemNamePlaceholder: "e.g. Venue Rental",
    vendorName: "Vendor Name",
    vendorNamePlaceholder: "e.g. Grand Palace",
    plannedCost: "Planned Cost",
    actualCost: "Actual Cost",
    paidAmount: "Amount Paid",
    dueDate: "Due Date",
    status: "Status",
    notes: "Notes",
    notesPlaceholder: "Optional notes…",
    all: "All",
    noItems: "No budget items yet",
    noItemsDesc: "Add your first expense to start tracking.",
    noResults: "No items match the selected category.",
    deleteConfirm: "Delete this budget item?",
    planned: "Planned",
    actual: "Actual",
    itemTitle: "Item Name",
    itemTitlePlaceholder: "e.g. Venue Rental",
    statusLabel: "Status",
    totalPlanned: "Total Planned",
    totalPaid: "Total Paid",
    ofBudget: "of budget used",
    used: "used",
    budgetOverview: "Budget Overview",
    emptyTitle: "No expenses yet",
    emptyDesc: "Add your first expense to track spending.",
    categories: {
      venue: "Venue",
      catering: "Catering",
      decor: "Decor",
      photo: "Photo & Video",
      music: "Music",
      restaurant: "Restaurant",
      photographer: "Photography",
      videographer: "Videography",
      decorations: "Decorations",
      flowers: "Flowers",
      invitations: "Invitations",
      website: "Website",
      host: "Host / MC",
      lighting: "Lighting",
      other: "Other",
    },
  },
  budgetStatus: {
    planned: "Planned",
    deposit_paid: "Deposit Paid",
    partially_paid: "Partially Paid",
    paid: "Paid",
    overdue: "Overdue",
    cancelled: "Cancelled",
    refunded: "Refunded",
  },
  generator: {
    title: "Generate Seating Plan",
    subtitle: "Choose a plan based on your confirmed guests.",
    comingGuests: "Coming Guests",
    seatsPerTable: "Seats per Table",
    preferredShape: "Preferred Shape",
    plans: "Suggested Plans",
    balanced: "Balanced",
    balancedDesc: "Even mix of round and rectangle tables.",
    compact: "Compact",
    compactDesc: "Fewer, larger tables to save space.",
    spacious: "Spacious",
    spaciousDesc: "More tables with fewer guests each.",
    applyPlan: "Apply Plan",
    applyConfirm: "This will replace existing tables. Guest list is preserved. Continue?",
    tablesOf: "tables of",
    capacity: "capacity",
    shape: "shape",
    guests: "coming guests",
    tables: "tables",
    seatsEach: "seats each",
    totalSeats: "total seats",
    warning: "Applying this plan will replace existing unlocked tables. Your guest list is preserved.",
    apply: "Apply Plan",
  },
  more: {
    title: "More",
    summary: "Summary",
    settings: "Settings",
    weddingDate: "Wedding Date",
    coupleName: "Couple Name",
    currency: "Currency",
    seatsPerTable: "Default Seats per Table",
    pricePerGuest: "Restaurant Price / Guest",
    dataManagement: "Data Management",
    exportJson: "Export JSON Backup",
    importJson: "Import JSON Backup",
    resetPlanner: "Reset Planner Data",
    resetConfirm: "Reset all planner data? This cannot be undone.",
    importError: "Invalid file. Please upload a valid planner backup.",
    importSuccess: "Data imported successfully.",
    exportSuccess: "Backup downloaded.",
    resetSuccess: "Planner has been reset.",
    prototypeNote: "Data is stored locally in your browser. This is a prototype.",
    futureFeatures: "Coming Soon",
    vendors: "Vendors",
    tasks: "Tasks",
    exportPdf: "Export PDF",
    printSeating: "Print Seating Plan",
    saveSettings: "Save Settings",
    editSettings: "Edit Settings",
    budgetPaid: "Budget Paid",
    items: "Expenses",
    exportData: "Export Backup",
    exportDesc: "Download a JSON backup of all your data",
    importData: "Import Backup",
    importDesc: "Restore data from a backup file",
    resetData: "Reset All Data",
    resetDesc: "Clear all data and start fresh",
    saved: "Saved!",
  },
  warnings: {
    guestAlreadyAssigned: "Guest is already assigned to another seat.",
    tableOverCapacity: "Table is over capacity.",
    replaceTablesWarning: "Applying this plan will replace unlocked tables. Guest list is preserved.",
    nameRequired: "Name is required.",
    titleRequired: "Title is required.",
    resetConfirm: "Reset all data? This cannot be undone.",
  },
  tasks: {
    title: "Tasks",
    subtitle: "Stay on top of your wedding to-do list.",
    addTask: "Add Task",
    editTask: "Edit Task",
    totalTasks: "Total",
    pending: "Pending",
    done: "Done",
    all: "All",
    noTasks: "No tasks yet",
    noTasksDesc: "Add your first task to stay organized.",
    noTasksDone: "Nothing completed yet",
    noTasksDoneDesc: "Complete tasks to see them here.",
    dueDate: "Due Date",
    priority: "Priority",
    taskTitle: "Task Title",
    titlePlaceholder: "e.g. Book photographer",
    notes: "Notes",
    notesPlaceholder: "Optional notes…",
    deleteConfirm: "Delete this task?",
    high: "High",
    medium: "Medium",
    low: "Low",
  },
  auth: {
    signInTitle: "Sign in to your wedding planner",
    signInSubtitle: "Use the access details provided by 4ever.am.",
    email: "Email",
    password: "Password or access code",
    signIn: "Sign In",
    signingIn: "Signing in...",
    invalidLogin: "Invalid login details.",
    noAccessTitle: "No planner access",
    noAccessText: "Planner access has not been assigned yet. Please contact 4ever.am.",
    contactSupport: "Need help? Contact 4ever.am",
    logout: "Log out",
  },
  planner: {
    loading: "Loading your planner...",
    projectNotFound: "Planner project not found.",
    assignedProject: "Assigned Wedding Project",
    customer: "Customer",
    couple: "Couple",
    weddingDate: "Wedding Date",
    template: "Template",
  },
} as const;

export type PlannerText = typeof plannerText;
