export type Locale = "en" | "hy";

// ─── English ──────────────────────────────────────────────────────────────────
const en = {
  app: {
    name: "4ever Planner",
    weddingDate: "Wedding Date",
    coupleName: "Aram & Ani",
    greeting: "Welcome back",
    greetingSub: "Here's what's happening with your wedding.",
  },
  nav: {
    dashboard: "Dashboard",
    guests: "Guests",
    tables: "Tables",
    tasks: "Tasks",
    budget: "Budget",
    more: "More",
    settings: "Settings",
  },
  common: {
    add: "Add",
    edit: "Edit",
    delete: "Delete",
    duplicate: "Duplicate",
    save: "Save",
    cancel: "Cancel",
    close: "Close",
    search: "Search",
    reset: "Reset",
    export: "Export",
    import: "Import",
    apply: "Apply",
    remove: "Remove",
    total: "Total",
    paid: "Paid",
    remaining: "Remaining",
    planned: "Planned",
    actual: "Actual",
    empty: "Empty",
    back: "Back",
    confirm: "Confirm",
    seats: "seats",
    guests: "guests",
    tables: "tables",
    of: "of",
    free: "free",
    seated: "seated",
    notes: "Notes",
    persons: "persons",
    all: "All",
  },
  dashboard: {
    title: "Dashboard",
    weddingOverview: "Wedding Overview",
    guestOverview: "Guest Overview",
    seatingOverview: "Seating Overview",
    budgetOverview: "Budget Overview",
    upcomingTasks: "Upcoming Tasks",
    recentExpenses: "Recent Expenses",
    quickActions: "Quick Actions",
    totalGuests: "Total Guests",
    tables: "Tables",
    totalSeated: "Seated",
    totalBudget: "Total Budget",
    coming: "Coming",
    waiting: "Waiting",
    notComing: "Not Coming",
    noResponse: "No Response",
    totalSeats: "Total Seats",
    freeSeats: "Free Seats",
    daysTo: "days to go",
    addGuest: "Add Guest",
    generatePlan: "Generate Seating Plan",
    addExpense: "Add Expense",
    weddingOf: "Wedding of",
    attending: "Attending",
    seated: "Seated",
    paid: "Paid",
    remaining: "Remaining",
    daysLeft: "days left",
    noGuests: "No guests added yet",
    filled: "filled",
    totalTables: "Tables",
    assigned: "Assigned",
    available: "Available",
    spent: "Spent",
    seeAllGuests: "See all guests",
    viewFloorPlan: "View floor plan",
    viewGuests: "View guests",
    viewTables: "View tables",
    viewSeating: "View seating",
    viewBudget: "View budget",
    seeAllTasks: "See all tasks",
    recentBudgetItems: "Recent Budget Items",
    viewAllExpenses: "View all expenses",
    welcomePrefix: "Welcome back,",
  },
  rsvp: {
    invited: "Invited",
    coming: "Coming",
    not_coming: "Not Coming",
    waiting: "Waiting",
    maybe: "Maybe",
  },
  guestSide: {
    bride: "Bride Side",
    groom: "Groom Side",
    both: "Both Sides",
    other: "Other",
  },
  guests: {
    title: "Guests",
    subtitle: "Manage your guest list and RSVP statuses.",
    searchPlaceholder: "Search guests...",
    totalGuests: "Total Guests",
    all: "All",
    coming: "Coming",
    waiting: "Waiting",
    notComing: "Not Coming",
    maybe: "Maybe",
    invited: "Invited",
    unseated: "Unseated",
    addGuest: "Add Guest",
    editGuest: "Edit Guest",
    fullName: "Full Name",
    fullNamePlaceholder: "e.g. Aram Petrosyan",
    phone: "Phone",
    phonePlaceholder: "+374…",
    email: "Email",
    emailPlaceholder: "email@example.com",
    rsvpStatus: "RSVP Status",
    guestCount: "Guest Count",
    side: "Side",
    groupName: "Group / Family",
    groupNamePlaceholder: "e.g. Petrosyan Family",
    dietaryNotes: "Dietary Notes",
    dietaryNotesPlaceholder: "Vegetarian, gluten-free…",
    notes: "Notes",
    notesPlaceholder: "Any additional notes…",
    tableAssignment: "Table",
    noGuests: "No guests yet",
    noGuestsDesc: "Add your first guest to start planning.",
    noResults: "No guests match your search.",
    deleteConfirm: "Delete this guest?",
    emptyTitle: "No guests yet",
    emptyDesc: "Add your first guest to start planning.",
    emptySearch: "No guests match your search.",
    noUnassignedGuests: "All coming guests are already seated.",
  },
  tables: {
    title: "Tables",
    subtitle: "Create tables, choose shapes, and assign guests to seats.",
    table: "Table",
    addTable: "Add Table",
    editTable: "Edit Table",
    deleteTable: "Delete Table",
    generatePlan: "Generate Seating Plan",
    manageSeats: "Manage Seats",
    locked: "Locked",
    tableName: "Table Name",
    tableNamePlaceholder: "e.g. Table 1, Head Table…",
    tableShape: "Shape",
    seatCount: "Number of Seats",
    notes: "Notes",
    notesPlaceholder: "Optional notes…",
    totalSeats: "Total Seats",
    seated: "Seated",
    free: "Free",
    noTables: "No tables yet",
    noTablesDesc: "Generate a seating plan or add a table manually.",
    noResults: "No tables match your search.",
    deleteConfirm: "Delete this table? Guests will be unassigned.",
    searchPlaceholder: "Search tables…",
    totalTables: "Tables",
    emptyTitle: "No tables yet",
    emptyDesc: "Generate a seating plan or add a table manually.",
    shape: "Shape",
    capacity: "Capacity",
    available: "Available",
  },
  tableShapes: {
    circle: "Round",
    square: "Square",
    rectangle: "Rectangle",
    long: "Long Banquet",
    oval: "Oval",
    head: "Head Table",
  },
  seats: {
    title: "Seat Assignment",
    assignedGuests: "Assigned Guests",
    emptySeat: "Empty",
    tapToAssign: "Tap a seat to assign or remove a guest",
    selectGuest: "Select Guest",
    searchGuest: "Search guest…",
    noUnassigned: "All coming guests are seated",
    assigned: "assigned",
    unassign: "Remove",
    seatLabel: "Seat",
    remove: "Remove",
    empty: "Empty Seat",
    assign: "Assign",
    pickGuest: "Pick a Guest",
  },
  budget: {
    title: "Budget",
    subtitle: "Track planned costs, payments and remaining expenses.",
    totalBudget: "Total Budget",
    estimatedBudget: "Estimated",
    paid: "Paid",
    remaining: "Remaining",
    addExpense: "Add Expense",
    editExpense: "Edit Expense",
    category: "Category",
    itemName: "Item Name",
    itemNamePlaceholder: "e.g. Venue Rental",
    vendorName: "Vendor Name",
    vendorNamePlaceholder: "e.g. Grand Palace",
    plannedCost: "Planned Cost",
    actualCost: "Actual Cost",
    paidAmount: "Amount Paid",
    dueDate: "Due Date",
    status: "Status",
    notes: "Notes",
    notesPlaceholder: "Optional notes…",
    all: "All",
    noItems: "No budget items yet",
    noItemsDesc: "Add your first expense to start tracking.",
    noResults: "No items match the selected category.",
    deleteConfirm: "Delete this budget item?",
    planned: "Planned",
    actual: "Actual",
    itemTitle: "Item Name",
    itemTitlePlaceholder: "e.g. Venue Rental",
    statusLabel: "Status",
    totalPlanned: "Total Planned",
    totalPaid: "Total Paid",
    ofBudget: "of budget used",
    used: "used",
    budgetOverview: "Budget Overview",
    emptyTitle: "No expenses yet",
    emptyDesc: "Add your first expense to track spending.",
    setBudgetCap: "Set Total Budget",
    budgetCapPlaceholder: "e.g. 50000",
    editBudgetCap: "Edit budget",
    customCategory: "Custom",
    customCategoryPlaceholder: "Category name…",
    attachReceipt: "Attach Receipt",
    viewReceipt: "View Receipt",
    removeReceipt: "Remove",
    categories: {
      venue: "Venue",
      catering: "Catering",
      decor: "Decor",
      photo: "Photo & Video",
      music: "Music",
      restaurant: "Restaurant",
      photographer: "Photography",
      videographer: "Videography",
      decorations: "Decorations",
      flowers: "Flowers",
      invitations: "Invitations",
      website: "Website",
      host: "Host / MC",
      lighting: "Lighting",
      other: "Other",
      custom: "Custom",
    },
  },
  budgetStatus: {
    planned: "Planned",
    deposit_paid: "Deposit Paid",
    partially_paid: "Partially Paid",
    paid: "Paid",
    overdue: "Overdue",
    cancelled: "Cancelled",
    refunded: "Refunded",
  },
  generator: {
    title: "Generate Seating Plan",
    subtitle: "Choose a plan based on your confirmed guests.",
    comingGuests: "Coming Guests",
    seatsPerTable: "Seats per Table",
    preferredShape: "Preferred Shape",
    plans: "Suggested Plans",
    balanced: "Balanced",
    balancedDesc: "Even mix of round and rectangle tables.",
    compact: "Compact",
    compactDesc: "Fewer, larger tables to save space.",
    spacious: "Spacious",
    spaciousDesc: "More tables with fewer guests each.",
    applyPlan: "Apply Plan",
    applyConfirm: "This will replace existing tables. Guest list is preserved. Continue?",
    tablesOf: "tables of",
    capacity: "capacity",
    shape: "shape",
    guests: "coming guests",
    tables: "tables",
    seatsEach: "seats each",
    totalSeats: "total seats",
    warning: "Applying this plan will replace existing unlocked tables. Your guest list is preserved.",
    apply: "Apply Plan",
  },
  more: {
    title: "More",
    summary: "Summary",
    settings: "Settings",
    weddingDate: "Wedding Date",
    coupleName: "Couple Name",
    currency: "Currency",
    seatsPerTable: "Default Seats per Table",
    pricePerGuest: "Restaurant Price / Guest",
    dataManagement: "Data Management",
    exportJson: "Export JSON Backup",
    importJson: "Import JSON Backup",
    resetPlanner: "Reset Planner Data",
    resetConfirm: "Reset all planner data? This cannot be undone.",
    importError: "Invalid file. Please upload a valid planner backup.",
    importSuccess: "Data imported successfully.",
    exportSuccess: "Backup downloaded.",
    resetSuccess: "Planner has been reset.",
    prototypeNote: "Data is stored locally in your browser. This is a prototype.",
    futureFeatures: "Coming Soon",
    vendors: "Vendors",
    tasks: "Tasks",
    exportPdf: "Export PDF",
    printSeating: "Print Seating Plan",
    saveSettings: "Save Settings",
    editSettings: "Edit Settings",
    budgetPaid: "Budget Paid",
    items: "Expenses",
    exportData: "Export Backup",
    exportDesc: "Download a JSON backup of all your data",
    importData: "Import Backup",
    importDesc: "Restore data from a backup file",
    resetData: "Reset All Data",
    resetDesc: "Clear all data and start fresh",
    saved: "Saved!",
    getFullAccess: "Get Full Access →",
    demoVersion: "DEMO",
    unlockTitle: "Unlock the Full Planner",
    unlockDesc: "Unlimited guests, tables, budget items, seat assignment, export & import — everything for your wedding day.",
    importLocalData: "Import saved planner data?",
    importLocalDataDesc: "Older browser-saved data was found. Import it into your planner database.",
    databaseNote: "Planner data is saved in your 4ever.am account.",
    contactUs: "Contact Us",
  },
  warnings: {
    guestAlreadyAssigned: "Guest is already assigned to another seat.",
    tableOverCapacity: "Table is over capacity.",
    replaceTablesWarning: "Applying this plan will replace unlocked tables. Guest list is preserved.",
    nameRequired: "Name is required.",
    titleRequired: "Title is required.",
    resetConfirm: "Reset all data? This cannot be undone.",
  },
  tasks: {
    title: "Tasks",
    subtitle: "Stay on top of your wedding to-do list.",
    addTask: "Add Task",
    editTask: "Edit Task",
    totalTasks: "Total",
    pending: "Pending",
    done: "Done",
    all: "All",
    noTasks: "No tasks yet",
    noTasksDesc: "Add your first task to stay organized.",
    noTasksDone: "Nothing completed yet",
    noTasksDoneDesc: "Complete tasks to see them here.",
    dueDate: "Due Date",
    priority: "Priority",
    taskTitle: "Task Title",
    titlePlaceholder: "e.g. Book photographer",
    notes: "Notes",
    notesPlaceholder: "Optional notes…",
    deleteConfirm: "Delete this task?",
    high: "High",
    medium: "Medium",
    low: "Low",
    markComplete: "Mark complete",
    markIncomplete: "Mark incomplete",
    reminderSection: "Reminder",
    reminderTime: "Reminder date & time",
    setReminder: "Send Telegram reminder",
    timezoneLabel: "Timezone",
    repeatInterval: "Repeat reminder",
    noRepeat: "No repeat",
    every10min: "Every 10 min",
    every30min: "Every 30 min",
    every1hour: "Every hour",
    every2hours: "Every 2 hours",
    every1day: "Once a day",
    telegramNotConnected: "Connect Telegram in Settings to enable reminders",
    importTasks: "You have {{count}} tasks saved locally. Import them?",
    importBtn: "Import",
    importLater: "Not now",
    reminderBadge: {
      scheduled: "Reminder set",
      sent: "Sent",
      repeating: "Repeating",
      stopped: "Stopped",
      completed: "Done via Telegram",
      failed: "Send failed",
    },
  },
  seats_screen: {
    overviewTab: "All",
    seatingTab: "Seating",
    assignedGuests: "Assigned Guests",
    noGuestsAssigned: "No guests assigned yet.",
    manageSeatBtn: "Manage Seats",
    seatLabel: "Seat",
  },
  auth: {
    signInTitle: "Sign in to your wedding planner",
    signInSubtitle: "Use the access details provided by 4ever.am.",
    email: "Email",
    password: "Password or access code",
    signIn: "Sign In",
    signingIn: "Signing in...",
    invalidLogin: "Invalid login details.",
    noAccessTitle: "No planner access",
    noAccessText: "Planner access has not been assigned yet. Please contact 4ever.am.",
    contactSupport: "Need help? Contact 4ever.am",
    logout: "Log out",
  },
  planner: {
    loading: "Loading your planner...",
    projectNotFound: "Planner project not found.",
    assignedProject: "Assigned Wedding Project",
    customer: "Customer",
    couple: "Couple",
    weddingDate: "Wedding Date",
    template: "Template",
  },
  telegram: {
    sectionTitle: "Telegram Notifications",
    sectionDesc: "Get task reminders sent directly to your Telegram.",
    notConnected: "Not connected",
    connected: "Connected",
    connectBtn: "Connect Telegram",
    disconnectBtn: "Disconnect",
    testBtn: "Send Test",
    testSent: "Test message sent!",
    testFailed: "Failed to send. Try again.",
    disconnectConfirm: "Disconnect Telegram notifications?",
    connectedSince: "Connected since",
    codeInstructions: "Open Telegram, find the bot, and send:",
    refreshBtn: "I've connected",
    copyBtn: "Copy",
    copiedBtn: "Copied!",
    expiresIn: "Code expires in 15 min",
  },
  tasksGreeting: {
    assistantLabel: "WEDDING ASSISTANT",
    greetingWithName: "Hi {{name}}! You have {{count}} task(s) to do.",
    genericGreeting: "You have {{count}} task(s) to do.",
    overdueSummary: "{{count}} overdue",
    todaySummary: "{{count}} today",
    pendingSummary: "{{count}} pending",
    moreTasks: "+ {{count}} more",
    viewTasks: "View all tasks",
    markFirstDone: "Mark first as done",
    markDone: "Mark done",
    dismiss: "Dismiss",
    overdue: "Overdue",
    today: "Today",
    upcoming: "Upcoming",
    noDate: "No date",
  },
} as const;

// ─── Armenian (Հայերեն) ───────────────────────────────────────────────────────
const hy = {
  app: {
    name: "4ever Planner",
    weddingDate: "Հարսանիքի ամսաթիվ",
    coupleName: "Արամ & Անի",
    greeting: "Բարի վերադարձ",
    greetingSub: "Նախագծեք ձեր հարսանիքը:",
  },
  nav: {
    dashboard: "Գլխավոր",
    guests: "Հյուրեր",
    tables: "Սեղաններ",
    tasks: "Առաջադր.",
    budget: "Բյուջե",
    more: "Այլ",
    settings: "Կարգավորումներ",
  },
  common: {
    add: "Ավելացնել",
    edit: "Խմբագրել",
    delete: "Ջնջել",
    duplicate: "Կրկնօրինակել",
    save: "Պահպանել",
    cancel: "Չեղարկել",
    close: "Փակել",
    search: "Որոնել",
    reset: "Վերականգնել",
    export: "Արտահանել",
    import: "Ներմուծել",
    apply: "Կիրառել",
    remove: "Հեռացնել",
    total: "Ընդամենը",
    paid: "Վճարված",
    remaining: "Մնացած",
    planned: "Պլանավորված",
    actual: "Փաստացի",
    empty: "Դատարկ",
    back: "Հետ",
    confirm: "Հաստատել",
    seats: "տեղ",
    guests: "հյուրեր",
    tables: "սեղաններ",
    of: "-ից",
    free: "ազատ",
    seated: "նստած",
    notes: "Նշումներ",
    persons: "անձ",
    all: "Բոլորը",
  },
  dashboard: {
    title: "Գլխավոր",
    weddingOverview: "Հարսանիքի ակնարկ",
    guestOverview: "Հյուրեր",
    seatingOverview: "Նստատեղեր",
    budgetOverview: "Բյուջե",
    upcomingTasks: "Անելիքներ",
    recentExpenses: "Վերջին ծախսեր",
    quickActions: "Արագ գործողություններ",
    totalGuests: "Ընդամենը Հյուրեր",
    tables: "Սեղաններ",
    totalSeated: "Նստեցված",
    totalBudget: "Ընդհանուր բյուջե",
    coming: "Գալիս է",
    waiting: "Անորոշ",
    notComing: "Չի գալիս",
    noResponse: "Չի պատասխանել",
    totalSeats: "Ընդամենը Տեղեր",
    freeSeats: "Ազատ տեղեր",
    daysTo: "օր մնաց",
    addGuest: "Ավելացնել հյուր",
    generatePlan: "Ստեղծել սեղանների պլան",
    addExpense: "Ավելացնել ծախս",
    weddingOf: "Հարսանիքը",
    attending: "Գալիս է",
    seated: "Նստեցված",
    paid: "Վճարված",
    remaining: "Մնացած",
    daysLeft: "օր մնաց",
    noGuests: "Հյուրեր դեռ չեն ավելացվել",
    filled: "լցված",
    totalTables: "Սեղաններ",
    assigned: "Նշանակված",
    available: "Հասանելի",
    spent: "Ծախսված",
    seeAllGuests: "Տեսնել բոլոր հյուրերին",
    viewFloorPlan: "Դիտել սեղանները",
    viewGuests: "Տեսնել հյուրերի ցանկը",
    viewTables: "Տեսնել սեղանները",
    viewSeating: "Տեսնել նստատեղերը",
    viewBudget: "Կառավարել բյուջեն",
    seeAllTasks: "Տեսնել բոլոր առաջադրանքները",
    recentBudgetItems: "Վերջին բյուջեի կետեր",
    viewAllExpenses: "Դիտել բոլոր ծախսերը",
    welcomePrefix: "Բարի վերադարձ,",
  },
  rsvp: {
    invited: "Հրավիրված",
    coming: "Գալիս է",
    not_coming: "Չի գալիս",
    waiting: "Սպասում ենք",
    maybe: "Հնարավոր է",
  },
  guestSide: {
    bride: "Հարսի կողմ",
    groom: "Փեսայի կողմ",
    both: "Երկու կողմ",
    other: "Այլ",
  },
  guests: {
    title: "Հյուրեր",
    subtitle: "Կառավարեք ձեր հյուրերի ցուցակը և պատասխանները:",
    searchPlaceholder: "Որոնել հյուրեր...",
    totalGuests: "Ընդամենը հյուրեր ",
    all: "Բոլորը",
    coming: "Գալիս է",
    waiting: "Սպասում ենք",
    notComing: "Չի գալիս",
    maybe: "Հնարավոր է",
    invited: "Հրավիրված",
    unseated: "Չնստեցված",
    addGuest: "Ավելացնել հյուր",
    editGuest: "Խմբագրել հյուրին",
    fullName: "Անուն ազգանուն",
    fullNamePlaceholder: "օր. Արամ Պետրոսյան",
    phone: "Հեռախոս",
    phonePlaceholder: "+374…",
    email: "Էլ. հասցե",
    emailPlaceholder: "email@example.com",
    rsvpStatus: "RSVP կարգավիճակ",
    guestCount: "Հյուրերի քանակ",
    side: "Կողմ",
    groupName: "Խումբ / Ընտանիք",
    groupNamePlaceholder: "օր. Պետրոսյանների ընտանիք",
    dietaryNotes: "Սննդային նախընտրություններ",
    dietaryNotesPlaceholder: "Բուսակեր, առանց գլուտեն…",
    notes: "Նշումներ",
    notesPlaceholder: "Լրացուցիչ նշումներ…",
    tableAssignment: "Սեղան",
    noGuests: "Հյուրեր դեռ չկան",
    noGuestsDesc: "Ավելացրեք ձեր առաջին հյուրին՝ պլանավորումը սկսելու համար:",
    noResults: "Ձեր որոնումով հյուրեր չեն գտնվել:",
    deleteConfirm: "Ջնջե՞լ այս հյուրին:",
    emptyTitle: "Հյուրեր դեռ չկան",
    emptyDesc: "Ավելացրեք ձեր առաջին հյուրին՝ պլանավորումը սկսելու համար:",
    emptySearch: "Ձեր որոնումով հյուրեր չեն գտնվել:",
    noUnassignedGuests: "Բոլոր եկող հյուրերն արդեն նստեցված են:",
  },
  tables: {
    title: "Սեղաններ",
    subtitle: "Ստեղծեք սեղաններ, ընտրեք սեղանի ձևը և նստեցրեք հյուրերին:",
    table: "Սեղան",
    addTable: "Ավելացնել սեղան",
    editTable: "Խմբագրել սեղանը",
    deleteTable: "Ջնջել սեղանը",
    generatePlan: "Ստեղծել նստատեղի պլան",
    manageSeats: "Կառավարել տեղերը",
    locked: "Կողպված",
    tableName: "Սեղանի անուն",
    tableNamePlaceholder: "օր. Սեղան 1, Գլխավոր սեղան…",
    tableShape: "Ձև",
    seatCount: "Տեղերի քանակ",
    notes: "Նշումներ",
    notesPlaceholder: "Ըստ ցանկության…",
    totalSeats: "Տեղեր ընդամենը",
    seated: "Նստած",
    free: "Ազատ",
    noTables: "Սեղաններ դեռ չկան",
    noTablesDesc: "Ստեղծեք նստատեղի պլան կամ ձեռքով ավելացրեք սեղան:",
    noResults: "Ձեր որոնումով սեղաններ չեն գտնվել:",
    deleteConfirm: "Ջնջե՞լ այս սեղանը: Հյուրերի նստատեղերը կջնջվեն:",
    searchPlaceholder: "Որոնել սեղաններ…",
    totalTables: "Ընդանուր սեղաններ",
    emptyTitle: "Սեղաններ դեռ չկան",
    emptyDesc: "Ստեղծեք նստատեղի պլան կամ ձեռքով ավելացրեք սեղան:",
    shape: "Ձև",
    capacity: "Տարողությունը",
    available: "Հասանելի",
  },
  tableShapes: {
    circle: "Կլոր",
    square: "Քառակուսի",
    rectangle: "Ուղղանկյուն",
    long: "Երկար բանկետ",
    oval: "Օվալ",
    head: "Գլխավոր սեղան",
  },
  seats: {
    title: "Նստատեղ",
    assignedGuests: "Նստեցված հյուրեր",
    emptySeat: "Դատարկ",
    tapToAssign: "Սեղմեք՝ հյուր նշանակելու կամ հեռացնելու համար",
    selectGuest: "Ընտրեք հյուրին",
    searchGuest: "Փնտրել հյուր…",
    noUnassigned: "Բոլոր եկող հյուրերը նստեցված են",
    assigned: "Նստեցված",
    unassign: "Հեռացնել",
    seatLabel: "Տեղ",
    remove: "Հեռացնել",
    empty: "Դատարկ տեղ",
    assign: "Նշանակել",
    pickGuest: "Ընտրեք հյուր",
  },
  budget: {
    title: "Բյուջե",
    subtitle: "Հետևեք պլանավորված ծախսերին, վճարումներին և մնացած ծախսերին:",
    totalBudget: "Ընդհանուր բյուջե",
    estimatedBudget: "Գնահատված",
    paid: "Վճարված",
    remaining: "Մնացած",
    addExpense: "Ավելացնել ծախս",
    editExpense: "Խմբագրել ծախսը",
    category: "Կատեգորիա",
    itemName: "Կետի անուն",
    itemNamePlaceholder: "օր. Դահլիճ վարձ",
    vendorName: "Մատակարար",
    vendorNamePlaceholder: "օր. Grand Palace",
    plannedCost: "Պլանավորված արժեք",
    actualCost: "Փաստացի արժեք",
    paidAmount: "Վճարված գումար",
    dueDate: "Վճարման ամսաթիվ",
    status: "Կարգավիճակ",
    notes: "Նշումներ",
    notesPlaceholder: "Ըստ ցանկության…",
    all: "Բոլորը",
    noItems: "Բյուջեի կետեր դեռ չկան",
    noItemsDesc: "Ավելացրեք ձեր առաջին ծախսը:",
    noResults: "Ընտրված կատեգորիայի կետեր չեն գտնվել:",
    deleteConfirm: "Ջնջե՞լ բյուջեի այս կետը:",
    planned: "Պլանավորված",
    actual: "Փաստացի",
    itemTitle: "Կետի անուն",
    itemTitlePlaceholder: "օր. Դահլիճ վարձ",
    statusLabel: "Կարգավիճակ",
    totalPlanned: "Ընդամենը պլանավորված",
    totalPaid: "Ընդամենը վճարված",
    ofBudget: "բյուջեից օգտագործված",
    used: "օգտագործված",
    budgetOverview: "Ընդանուր բյուջե",
    emptyTitle: "Ծախսեր դեռ չկան",
    emptyDesc: "Ավելացրեք ձեր առաջին ծախսը:",
    setBudgetCap: "Սահմանել ընդհանուր բյուջե",
    budgetCapPlaceholder: "օր. 50000",
    editBudgetCap: "Խմբագրել բյուջե",
    customCategory: "Հատուկ",
    customCategoryPlaceholder: "Կատեգորիայի անուն…",
    attachReceipt: "Կցել անդորրագիր",
    viewReceipt: "Տեսնել անդորրագիրը",
    removeReceipt: "Հեռացնել",
    categories: {
      venue: "Դահլիճ",
      catering: "Սնունդ",
      decor: "Զարդարանք",
      photo: "Լուսանկար և Տեսանյութ",
      music: "Երաժշտություն",
      restaurant: "Ռեստորան",
      photographer: "Լուսանկարիչ",
      videographer: "Տեսաձայնագրող",
      decorations: "Զարդարանք",
      flowers: "Ծաղիկներ",
      invitations: "Հրավիրատոմսեր",
      website: "Կայք",
      host: "Թամադա",
      lighting: "Լուսավորություն",
      other: "Այլ",
      custom: "Հատուկ",
    },
  },
  budgetStatus: {
    planned: "Պլանավորված",
    deposit_paid: "Կանխավճար",
    partially_paid: "Մասամբ վճարված",
    paid: "Վճարված",
    overdue: "Ժամկետանց",
    cancelled: "Չեղարկված",
    refunded: "Վերադարձված",
  },
  generator: {
    title: "Ստեղծել նստատեղի պլան",
    subtitle: "Ընտրեք պլան՝ ելնելով հաստատված հյուրերից:",
    comingGuests: "Եկող հյուրեր",
    seatsPerTable: "Տեղ մեկ սեղանին",
    preferredShape: "Նախընտրելի ձև",
    plans: "Առաջարկվող պլաններ",
    balanced: "Հավասարակշռված",
    balancedDesc: "Կլոր և ուղղանկյուն սեղանների հավասար խառնուրդ:",
    compact: "Կոմպակտ",
    compactDesc: "Ավելի քիչ, մեծ սեղաններ՝ տարածք խնայելու համար:",
    spacious: "Ընդարձակ",
    spaciousDesc: "Ավելի շատ սեղաններ՝ ավելի քիչ հյուրերով:",
    applyPlan: "Կիրառել պլանը",
    applyConfirm: "Սա կփոխարինի առկա սեղաններին: Հյուրերի ցուցակը կպահպանվի:",
    tablesOf: "սեղան",
    capacity: "տարողություն",
    shape: "ձև",
    guests: "եկող հյուրեր",
    tables: "սեղաններ",
    seatsEach: "տեղ",
    totalSeats: "տեղ ընդամենը",
    warning: "Պլանի կիրառումը կփոխարինի չկողպված սեղաններին: Հյուրերի ցուցակը կպահպանվի:",
    apply: "Կիրառել պլանը",
  },
  more: {
    title: "Այլ",
    summary: "Ամփոփ",
    settings: "Կարգավորումներ",
    weddingDate: "Հարսանիքի ամսաթիվ",
    coupleName: "Զույգի անուն",
    currency: "Արժույթ",
    seatsPerTable: "Տեղ մեկ սեղանի համար",
    pricePerGuest: "Ռեստորան / հյուր",
    dataManagement: "Տվյալների կառավարում",
    exportJson: "Արտահանել JSON կրկնօրինակ",
    importJson: "Ներմուծել JSON կրկնօրինակ",
    resetPlanner: "Վերականգնել բոլոր տվյալները",
    resetConfirm: "Վերականգնել բոլոր տվյալները: Հնարավոր չի լինի հետ բերել:",
    importError: "Անվավեր ֆայլ: Բեռնեք վավեր կրկնօրինակ:",
    importSuccess: "Տվյալները հաջողությամբ ներմուծվեցին:",
    exportSuccess: "Կրկնօրինակը բեռնված է:",
    resetSuccess: "Ծրագիրը վերականգնել է:",
    prototypeNote: "Տվյալները պահվում են ձեր բրաուզերում: Սա նախատիպ է:",
    futureFeatures: "Շուտով",
    vendors: "Մատակարարներ",
    tasks: "Առաջադրանքներ",
    exportPdf: "Արտահանել PDF",
    printSeating: "Տպել նստատեղի պլանը",
    saveSettings: "Պահպանել",
    editSettings: "Խմբագրել",
    budgetPaid: "Վճարված բյուջե",
    items: "Ծախսեր",
    exportData: "Արտահանել կրկնօրինակ",
    exportDesc: "Բեռնել JSON կրկնօրինակ ձեր բոլոր տվյալներից",
    importData: "Ներմուծել կրկնօրինակ",
    importDesc: "Վերականգնել տվյալները կրկնօրինակից",
    resetData: "Վերականգնել բոլոր տվյալները",
    resetDesc: "Մաքրել բոլոր տվյալները",
    saved: "Պահպանված!",
    getFullAccess: "Ստանալ լիարժեք մուտք →",
    demoVersion: "Փորձնական տարբերակ",
    unlockTitle: "Բացեք լիարժեք ծրագիրը",
    unlockDesc: "Անսահմանափակ հյուրեր, սեղաններ, բյուջե, նստատեղ, արտահանում — ամեն ինչ ձեր հարսանիքի համար:",
    importLocalData: "Import saved planner data?",
    importLocalDataDesc: "Older browser-saved data was found. Import it into your planner database.",
    databaseNote: "Planner data is saved in your 4ever.am account.",
    contactUs: "Կապ հաստատել",
  },
  warnings: {
    guestAlreadyAssigned: "Հյուրն արդեն մեկ այլ տեղ նշանակված է:",
    tableOverCapacity: "Սեղանը ծանրաբեռնված է:",
    replaceTablesWarning: "Այս պլանի կիրառումը կփոխարինի չկողպված սեղաններին: Հյուրերի ցուցակը կպահպանվի:",
    nameRequired: "Անունը պարտադիր է:",
    titleRequired: "Վերնագիրը պարտադիր է:",
    resetConfirm: "Վերականգնել բոլոր տվյալները: Հնարավոր չի լինի հետ բերել:",
  },
  tasks: {
    title: "Առաջադրանքներ",
    subtitle: "Հետևեք ձեր հարսանիքի կարևոր գործերին:",
    addTask: "Ավելացնել առաջադրանք",
    editTask: "Խմբագրել առաջադրանքը",
    totalTasks: "Ընդամենը",
    pending: "Ընթացքում",
    done: "Կատարված",
    all: "Բոլորը",
    noTasks: "Առաջադրանքներ դեռ չկան",
    noTasksDesc: "Ավելացրեք ձեր առաջին առաջադրանքը:",
    noTasksDone: "Դեռ ոչինչ չի կատարվել",
    noTasksDoneDesc: "Կատարեք առաջադրանքներ՝ դրանք տեսնելու համար:",
    dueDate: "Վերջնաժամկետ",
    priority: "Առաջնահերթություն",
    taskTitle: "Առաջադրանքի վերնագիր",
    titlePlaceholder: "օր. Պայմանավորվել լուսանկարչի հետ",
    notes: "Նշումներ",
    notesPlaceholder: "Ըստ ցանկության…",
    deleteConfirm: "Ջնջե՞լ առաջադրանքը:",
    high: "Բարձր",
    medium: "Միջին",
    low: "Ցածր",
    markComplete: "Նշել կատարված",
    markIncomplete: "Նշել կատարված չէ",
    reminderSection: "Հիշեցում",
    reminderTime: "Հիշեցման ամսաթիվ ու ժամ",
    setReminder: "Ուղարկել Telegram հիշեցում",
    timezoneLabel: "Ժամային գոտի",
    repeatInterval: "Կրկնել",
    noRepeat: "Առանց կրկնության",
    every10min: "Ամեն 10 րոպե",
    every30min: "Ամեն 30 րոպե",
    every1hour: "Ամեն ժամ",
    every2hours: "Ամեն 2 ժամ",
    every1day: "Օրական մեկ անգամ",
    telegramNotConnected: "Կապեք Telegram-ը Կարգավորումներում հիշեցումներ ստանալու համար",
    importTasks: "Ունեք {{count}} պահված առաջադրանք: Ներմուծե՞լ:",
    importBtn: "Ներմուծել",
    importLater: "Հետո",
    reminderBadge: {
      scheduled: "Հիշեցում սահմանված է",
      sent: "Ուղարկված",
      repeating: "Կրկնվում է",
      stopped: "Դադարեցված",
      completed: "Կատարված Telegram-ով",
      failed: "Չի ուղարկվել",
    },
  },
  seats_screen: {
    overviewTab: "Բոլորը",
    seatingTab: "Նստատեղ",
    assignedGuests: "Նստեցված հյուրեր",
    noGuestsAssigned: "Հյուրեր դեռ չեն նստեցվել:",
    manageSeatBtn: "Կառավարել տեղերը",
    seatLabel: "Տեղ",
  },
  auth: {
    signInTitle: "Մուտք գործեք ձեր հարսանիքի ծրագիր",
    signInSubtitle: "Օգտագործեք 4ever.am-ի կողմից տրամադրված մուտքի տվյալները:",
    email: "Էլ. հասցե",
    password: "Գաղտնաբառ կամ մուտքի կոդ",
    signIn: "Մուտք",
    signingIn: "Խնդրում ենք սպասել...",
    invalidLogin: "Սխալ մուտքի տվյալներ:",
    noAccessTitle: "Ծրագիրը հասանելի չէ",
    noAccessText: "Դուք չունեք հասանելիություն: Կապվեք 4ever.am-ի հետ:",
    contactSupport: "Օգնության կարի՞ք ունեք : Կապվեք 4ever.am-ի հետ",
    logout: "Ելք",
  },
  planner: {
    loading: "Ձեր ծրագիրը բեռնվում է ...",
    projectNotFound: "Հարսանիքի ծրագիրը չի գտնվել:",
    assignedProject: "Նշանակված հարսանիքի ծրագիր",
    customer: "Հաճախորդ",
    couple: "Զույգ",
    weddingDate: "Հարսանիքի ամսաթիվ",
    template: "Ձևանմուշ",
  },
  telegram: {
    sectionTitle: "Telegram ծանուցումներ",
    sectionDesc: "Ստացեք առաջադրանքների հիշեցումներ Telegram-ի միջոցով:",
    notConnected: "Կապ չկա",
    connected: "Կապված է",
    connectBtn: "Կապել Telegram",
    disconnectBtn: "Անջատել",
    testBtn: "Ուղարկել թեստ",
    testSent: "Թեստ հաղորդագրությունն ուղարկվեց!",
    testFailed: "Ուղարկումը ձախողվեց: Կրկին փորձեք:",
    disconnectConfirm: "Անջատե՞լ Telegram ծանուցումները:",
    connectedSince: "Կապված է",
    codeInstructions: "Բացեք Telegram, գտեք բոտը և ուղարկեք:",
    refreshBtn: "Ես կապվել եմ",
    copyBtn: "Պատճենել",
    copiedBtn: "Պատճենված!",
    expiresIn: "Կոդն ուժի մեջ է 15 ր",
  },
  tasksGreeting: {
    assistantLabel: "ՀԱՐՍ. ՕԳՆԱԿԱՆ",
    greetingWithName: "Բարև, {{name}}! Ունեք {{count}} կատ. առաջ.:",
    genericGreeting: "Ունեք {{count}} կատ. առաջ.:",
    overdueSummary: "{{count}} ժամկ. անց",
    todaySummary: "{{count}} այսօր",
    pendingSummary: "{{count}} ընդ.",
    moreTasks: "+ ևս {{count}}",
    viewTasks: "Տեսնել առ.",
    markFirstDone: "Կատ. 1-ինը",
    markDone: "Կատ.",
    dismiss: "Փակել",
    overdue: "Ժամկ. անց",
    today: "Այսօր",
    upcoming: "Շուտով",
    noDate: "Ամ. չկա",
  },
} as const;

// ─── Exports ──────────────────────────────────────────────────────────────────
export const plannerLocales = { en, hy } as const;

export function getPlannerText(locale: Locale): PlannerText {
  return plannerLocales[locale] as PlannerText;
}

export type PlannerText = typeof en;

// Keep backward-compat export so any file not yet migrated still compiles
export const plannerText = en;
