/**
 * demoPalettes.ts
 *
 * 35 curated wedding color palettes for the customer demo flow.
 * Each palette maps to WeddingConfig.theme.colors keys so it can be applied
 * directly with updateConfig({ theme: { colors: palette.colors } }).
 *
 * SAFE: This file is demo-only. It does not modify any live template or config.
 *
 * Color role reference (matches AureliaTemplate / FlorenceTemplate C-block):
 *   primary         → gold / accent buttons & highlights
 *   secondary       → dark section backgrounds (hero, roadmap, gallery, RSVP, footer)
 *   background      → light section backgrounds (story, details, venue)
 *   textColor       → body text on LIGHT sections  (maps to C.ivoryMuted)
 *   lightText       → text on DARK sections         (maps to C.textLight)
 *   mutedText       → secondary text on dark sections (maps to C.textMuted)
 *   cardBackground  → detail/venue card fill
 *   cardBorder      → detail card border chrome
 *   accent          → legacy alias (used by classic/romantic templates)
 *   buttonColor     → legacy alias (used by classic/romantic templates)
 */

export interface DemoPalette {
  id: string;
  name: string;
  mood: string;
  colors: {
    primary: string;
    secondary: string;
    accent: string;
    background: string;
    textColor: string;
    lightText: string;
    mutedText: string;
    cardBackground: string;
    cardBorder: string;
    buttonColor: string;
  };
}

export const DEMO_PALETTES: DemoPalette[] = [
  // ─── Dark / Moody ────────────────────────────────────────────────────────────
  {
    id: "david-rose",
    name: "David & Rose",
    mood: "Classic dark wine",
    colors: {
      primary: "#5B2333",
      secondary: "#3a1520",
      accent: "#b9b1a7",
      background: "#F9F7F6",
      textColor: "#2a0e18",
      lightText: "#FAF0EC",
      mutedText: "#C4A0A8",
      cardBackground: "#F2ECEA",
      cardBorder: "#D4B8BE",
      buttonColor: "#5B2333",
    },
  },
  {
    id: "dark-velvet",
    name: "Dark Velvet",
    mood: "Deep burgundy noir",
    colors: {
      primary: "#c8a882",
      secondary: "#1a0a0e",
      accent: "#d4b896",
      background: "#FDF6F0",
      textColor: "#2e1810",
      lightText: "#f5ede4",
      mutedText: "#b89880",
      cardBackground: "#EFE8E0",
      cardBorder: "#D4C4B4",
      buttonColor: "#c8a882",
    },
  },
  {
    id: "black-onyx",
    name: "Black Onyx",
    mood: "Dramatic black & gold",
    colors: {
      primary: "#d4af37",
      secondary: "#0d0d0d",
      accent: "#f0c040",
      background: "#FAFAF8",
      textColor: "#1c1810",
      lightText: "#f5f0e0",
      mutedText: "#b8a870",
      cardBackground: "#EDEDE8",
      cardBorder: "#D4D0B8",
      buttonColor: "#d4af37",
    },
  },
  {
    id: "obsidian-rose",
    name: "Obsidian Rose",
    mood: "Moody dark romance",
    colors: {
      primary: "#e8c4b8",
      secondary: "#160d0b",
      accent: "#f5ddd5",
      background: "#FDF8F6",
      textColor: "#2e1810",
      lightText: "#f5ede4",
      mutedText: "#c4a098",
      cardBackground: "#F0E8E4",
      cardBorder: "#D8C8C0",
      buttonColor: "#c9a090",
    },
  },
  {
    id: "noir-plum",
    name: "Noir Plum",
    mood: "Dark purple evening",
    colors: {
      primary: "#c4a7d4",
      secondary: "#100a14",
      accent: "#e0c8f0",
      background: "#FAF6FC",
      textColor: "#2e1840",
      lightText: "#f0e8f8",
      mutedText: "#b898c8",
      cardBackground: "#EDE4F4",
      cardBorder: "#D4C8E8",
      buttonColor: "#8b6b9e",
    },
  },
  {
    id: "dark-forest-gold",
    name: "Dark Forest",
    mood: "Deep woodland dusk",
    colors: {
      primary: "#c8b87a",
      secondary: "#0d1208",
      accent: "#e0d09a",
      background: "#F8F6F0",
      textColor: "#1e1c10",
      lightText: "#f0ead8",
      mutedText: "#b0a878",
      cardBackground: "#EDEADC",
      cardBorder: "#D4CCAC",
      buttonColor: "#c8b87a",
    },
  },
  {
    id: "espresso-cream",
    name: "Espresso Cream",
    mood: "Rich warm darkness",
    colors: {
      primary: "#d4b896",
      secondary: "#1c1009",
      accent: "#ecd8bc",
      background: "#FDF8F4",
      textColor: "#2a1c10",
      lightText: "#f5ede0",
      mutedText: "#c0a080",
      cardBackground: "#EEE4D8",
      cardBorder: "#D8C8B4",
      buttonColor: "#9c7c5c",
    },
  },
  {
    id: "slate-ivory",
    name: "Slate Ivory",
    mood: "Cool charcoal luxury",
    colors: {
      primary: "#e8e0d4",
      secondary: "#1a1a1e",
      accent: "#f0e8dc",
      background: "#F8F8F6",
      textColor: "#1e1e22",
      lightText: "#f0ece4",
      mutedText: "#b4b0a8",
      cardBackground: "#EDECE8",
      cardBorder: "#D4D0C8",
      buttonColor: "#9a9488",
    },
  },
  {
    id: "deep-wine",
    name: "Deep Wine",
    mood: "Velvety dark crimson",
    colors: {
      primary: "#f5ddd5",
      secondary: "#2a0a10",
      accent: "#f8ece4",
      background: "#FDF6F4",
      textColor: "#2e1014",
      lightText: "#faf0ec",
      mutedText: "#c8a4A0",
      cardBackground: "#F0E4E0",
      cardBorder: "#DCC8C4",
      buttonColor: "#c09080",
    },
  },
  {
    id: "dark-sage",
    name: "Dark Sage",
    mood: "Dusky garden evening",
    colors: {
      primary: "#b8d4b0",
      secondary: "#0a140c",
      accent: "#d0e8c8",
      background: "#F4FAF4",
      textColor: "#142010",
      lightText: "#e8f4e4",
      mutedText: "#98c090",
      cardBackground: "#E4F0E0",
      cardBorder: "#C8DCC4",
      buttonColor: "#7a9c74",
    },
  },
  {
    id: "midnight-gold",
    name: "Midnight Gold",
    mood: "Opulent evening",
    colors: {
      primary: "#d97706",
      secondary: "#1c1917",
      accent: "#fbbf24",
      background: "#FDFAF4",
      textColor: "#1c1810",
      lightText: "#fef3c7",
      mutedText: "#c8a860",
      cardBackground: "#EEE8D8",
      cardBorder: "#D8CCA8",
      buttonColor: "#d97706",
    },
  },
  {
    id: "luxury-dark",
    name: "Luxury Dark",
    mood: "Dramatic modern",
    colors: {
      primary: "#c7d2fe",
      secondary: "#0f0e17",
      accent: "#7c3aed",
      background: "#F8F6FF",
      textColor: "#1e1b4b",
      lightText: "#e0e7ff",
      mutedText: "#a8b4d8",
      cardBackground: "#ECEAFA",
      cardBorder: "#D4D0F0",
      buttonColor: "#7c3aed",
    },
  },

  // ─── Light / Romantic ─────────────────────────────────────────────────────────
  {
    id: "romantic-rose",
    name: "Romantic Rose",
    mood: "Classic romantic",
    colors: {
      primary: "#9f1239",
      secondary: "#fda4af",
      accent: "#be185d",
      background: "#fff1f2",
      textColor: "#3b0a1f",
      lightText: "#fff1f2",
      mutedText: "#9f5060",
      cardBackground: "#FDEAEC",
      cardBorder: "#F4C0C8",
      buttonColor: "#9f1239",
    },
  },
  {
    id: "classic-ivory",
    name: "Classic Ivory",
    mood: "Timeless elegant",
    colors: {
      primary: "#78350f",
      secondary: "#fde68a",
      accent: "#d97706",
      background: "#fffbeb",
      textColor: "#1c1917",
      lightText: "#fffbeb",
      mutedText: "#92602a",
      cardBackground: "#FFF6D8",
      cardBorder: "#EDD898",
      buttonColor: "#78350f",
    },
  },
  {
    id: "sage-garden",
    name: "Sage Garden",
    mood: "Fresh botanical",
    colors: {
      primary: "#3d6b4f",
      secondary: "#bbf7d0",
      accent: "#16a34a",
      background: "#f0fdf4",
      textColor: "#14532d",
      lightText: "#f0fdf4",
      mutedText: "#4a8060",
      cardBackground: "#DFFAEB",
      cardBorder: "#B4E8C8",
      buttonColor: "#3d6b4f",
    },
  },
  {
    id: "gold-beige",
    name: "Gold Beige",
    mood: "Warm luxurious",
    colors: {
      primary: "#92400e",
      secondary: "#fde68a",
      accent: "#b45309",
      background: "#fefce8",
      textColor: "#3d2b00",
      lightText: "#fefce8",
      mutedText: "#a07030",
      cardBackground: "#FFF6C8",
      cardBorder: "#EDD888",
      buttonColor: "#92400e",
    },
  },
  {
    id: "blush-pearl",
    name: "Blush Pearl",
    mood: "Soft feminine",
    colors: {
      primary: "#be185d",
      secondary: "#fce7f3",
      accent: "#ec4899",
      background: "#fdf2f8",
      textColor: "#4a1942",
      lightText: "#fdf2f8",
      mutedText: "#a05070",
      cardBackground: "#FAE4F4",
      cardBorder: "#F0C0DC",
      buttonColor: "#be185d",
    },
  },
  {
    id: "champagne-cream",
    name: "Champagne Cream",
    mood: "Understated elegant",
    colors: {
      primary: "#a16207",
      secondary: "#fef3c7",
      accent: "#ca8a04",
      background: "#fefdf9",
      textColor: "#292524",
      lightText: "#fefdf9",
      mutedText: "#8a6820",
      cardBackground: "#FEF8E4",
      cardBorder: "#EDE0A8",
      buttonColor: "#a16207",
    },
  },
  {
    id: "dusty-blue",
    name: "Dusty Blue",
    mood: "Serene cool",
    colors: {
      primary: "#1d4ed8",
      secondary: "#bfdbfe",
      accent: "#3b82f6",
      background: "#eff6ff",
      textColor: "#1e3a5f",
      lightText: "#eff6ff",
      mutedText: "#4070B0",
      cardBackground: "#DCEEFF",
      cardBorder: "#B4CCEA",
      buttonColor: "#1d4ed8",
    },
  },
  {
    id: "lavender-mist",
    name: "Lavender Mist",
    mood: "Dreamy floral",
    colors: {
      primary: "#7e22ce",
      secondary: "#e9d5ff",
      accent: "#9333ea",
      background: "#faf5ff",
      textColor: "#3b0764",
      lightText: "#faf5ff",
      mutedText: "#8050A0",
      cardBackground: "#F0E4FF",
      cardBorder: "#DCC4F8",
      buttonColor: "#7e22ce",
    },
  },
  {
    id: "olive-gold",
    name: "Olive Gold",
    mood: "Earthy warm",
    colors: {
      primary: "#3f6212",
      secondary: "#d9f99d",
      accent: "#65a30d",
      background: "#f7fee7",
      textColor: "#1a2e05",
      lightText: "#f7fee7",
      mutedText: "#5a7820",
      cardBackground: "#EDFAC8",
      cardBorder: "#C8E894",
      buttonColor: "#3f6212",
    },
  },
  {
    id: "burgundy-blush",
    name: "Burgundy Blush",
    mood: "Deep romantic",
    colors: {
      primary: "#7f1d1d",
      secondary: "#fecaca",
      accent: "#b91c1c",
      background: "#fff5f5",
      textColor: "#3b0606",
      lightText: "#fff5f5",
      mutedText: "#9a5050",
      cardBackground: "#FDEAEA",
      cardBorder: "#F4C4C4",
      buttonColor: "#7f1d1d",
    },
  },
  {
    id: "pearl-navy",
    name: "Pearl Navy",
    mood: "Sophisticated",
    colors: {
      primary: "#1e3a5f",
      secondary: "#e2e8f0",
      accent: "#334155",
      background: "#f8fafc",
      textColor: "#0f172a",
      lightText: "#f8fafc",
      mutedText: "#4a6080",
      cardBackground: "#EBF0F8",
      cardBorder: "#C4D0E0",
      buttonColor: "#1e3a5f",
    },
  },
  {
    id: "terracotta-linen",
    name: "Terracotta Linen",
    mood: "Rustic warm",
    colors: {
      primary: "#9a3412",
      secondary: "#fed7aa",
      accent: "#ea580c",
      background: "#fff7ed",
      textColor: "#431407",
      lightText: "#fff7ed",
      mutedText: "#A05030",
      cardBackground: "#FEF0DC",
      cardBorder: "#F0D0A8",
      buttonColor: "#9a3412",
    },
  },
  {
    id: "emerald-ivory",
    name: "Emerald Ivory",
    mood: "Lush garden",
    colors: {
      primary: "#065f46",
      secondary: "#a7f3d0",
      accent: "#059669",
      background: "#ecfdf5",
      textColor: "#022c22",
      lightText: "#ecfdf5",
      mutedText: "#207858",
      cardBackground: "#D8FAEC",
      cardBorder: "#A8E8CC",
      buttonColor: "#065f46",
    },
  },
  {
    id: "soft-peach",
    name: "Soft Peach",
    mood: "Gentle sunrise",
    colors: {
      primary: "#c2410c",
      secondary: "#fed7aa",
      accent: "#f97316",
      background: "#fff7ed",
      textColor: "#431407",
      lightText: "#fff7ed",
      mutedText: "#B06030",
      cardBackground: "#FEF0DC",
      cardBorder: "#F0D0A8",
      buttonColor: "#c2410c",
    },
  },
  {
    id: "rosewood",
    name: "Rosewood",
    mood: "Rich floral",
    colors: {
      primary: "#881337",
      secondary: "#fecdd3",
      accent: "#e11d48",
      background: "#fff1f2",
      textColor: "#3b0a1f",
      lightText: "#fff1f2",
      mutedText: "#A05060",
      cardBackground: "#FDE4E8",
      cardBorder: "#F4C0C8",
      buttonColor: "#881337",
    },
  },
  {
    id: "warm-sand",
    name: "Warm Sand",
    mood: "Desert minimal",
    colors: {
      primary: "#78350f",
      secondary: "#e7d5c1",
      accent: "#a16207",
      background: "#fdf8f2",
      textColor: "#1c1917",
      lightText: "#fdf8f2",
      mutedText: "#907050",
      cardBackground: "#F5EDE0",
      cardBorder: "#E0D0B8",
      buttonColor: "#78350f",
    },
  },
  {
    id: "silver-sage",
    name: "Silver Sage",
    mood: "Cool botanical",
    colors: {
      primary: "#475569",
      secondary: "#cbd5e1",
      accent: "#64748b",
      background: "#f8fafc",
      textColor: "#0f172a",
      lightText: "#f8fafc",
      mutedText: "#6080A0",
      cardBackground: "#EBF0F8",
      cardBorder: "#C4D0E0",
      buttonColor: "#475569",
    },
  },
  {
    id: "cocoa-cream",
    name: "Cocoa Cream",
    mood: "Cozy elegant",
    colors: {
      primary: "#44403c",
      secondary: "#d6d3d1",
      accent: "#78716c",
      background: "#fafaf9",
      textColor: "#1c1917",
      lightText: "#fafaf9",
      mutedText: "#706860",
      cardBackground: "#F0EDEC",
      cardBorder: "#D8D0CC",
      buttonColor: "#44403c",
    },
  },
  {
    id: "ivory-garden",
    name: "Ivory Garden",
    mood: "Romantic natural",
    colors: {
      primary: "#166534",
      secondary: "#dcfce7",
      accent: "#15803d",
      background: "#fefffe",
      textColor: "#14532d",
      lightText: "#fefffe",
      mutedText: "#407860",
      cardBackground: "#E8FAEE",
      cardBorder: "#B8E8CC",
      buttonColor: "#166534",
    },
  },
  {
    id: "mauve-romance",
    name: "Mauve Romance",
    mood: "Dusty vintage",
    colors: {
      primary: "#86198f",
      secondary: "#f5d0fe",
      accent: "#a21caf",
      background: "#fdf4ff",
      textColor: "#3b0764",
      lightText: "#fdf4ff",
      mutedText: "#9050A0",
      cardBackground: "#F4E4FF",
      cardBorder: "#E0C0F8",
      buttonColor: "#86198f",
    },
  },
  {
    id: "antique-gold",
    name: "Antique Gold",
    mood: "Heritage luxury",
    colors: {
      primary: "#713f12",
      secondary: "#fef9c3",
      accent: "#ca8a04",
      background: "#fefce8",
      textColor: "#292524",
      lightText: "#fefce8",
      mutedText: "#906820",
      cardBackground: "#FEF6C0",
      cardBorder: "#EEE090",
      buttonColor: "#713f12",
    },
  },
  {
    id: "wine-velvet",
    name: "Wine Velvet",
    mood: "Deep velvet",
    colors: {
      primary: "#4c1d95",
      secondary: "#ddd6fe",
      accent: "#7c3aed",
      background: "#f5f3ff",
      textColor: "#1e1b4b",
      lightText: "#f5f3ff",
      mutedText: "#6050B0",
      cardBackground: "#EDE8FF",
      cardBorder: "#CCC4F8",
      buttonColor: "#4c1d95",
    },
  },
  {
    id: "forest-cream",
    name: "Forest Cream",
    mood: "Woodland fresh",
    colors: {
      primary: "#14532d",
      secondary: "#bbf7d0",
      accent: "#15803d",
      background: "#f0fdf4",
      textColor: "#052e16",
      lightText: "#f0fdf4",
      mutedText: "#307848",
      cardBackground: "#DCFAEC",
      cardBorder: "#A8E8C0",
      buttonColor: "#14532d",
    },
  },
];

/** Look up a palette by id, returns undefined if not found */
export function getPaletteById(id: string): DemoPalette | undefined {
  return DEMO_PALETTES.find(p => p.id === id);
}
